In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Arrays

In [2]:
heights = make_array(67, 60, 71, 63, 65)
heights

array([67, 60, 71, 63, 65])

In [3]:
heights / 12

array([5.58333333, 5.        , 5.91666667, 5.25      , 5.41666667])

In [9]:
sum(heights)

326

In [4]:
len(heights)

5

In [5]:
sum(heights)

326

In [6]:
sum(heights) / len(heights)

65.2

In [7]:
np.average(heights)

65.2

In [10]:
strings_array = make_array('ok', 'ya', 'hm')
strings_array

array(['ok', 'ya', 'hm'], dtype='<U2')

In [11]:
strings_array * 2



UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U3'), dtype('<U3')) -> dtype('<U3')

In [12]:
'ok' * 2

'okok'

In [13]:
heights

array([67, 60, 71, 63, 65])

In [14]:
heights.item(3) # the element in position 3 (or the 4th element) is 63

63

In [15]:
len(heights) # there are 5 elements in the array, heights

5

In [16]:
heights.item(0)

67

In [18]:
heights.item(5)

IndexError: index 5 is out of bounds for axis 0 with size 5

In [22]:
strings_array.item(3)

IndexError: index 3 is out of bounds for axis 0 with size 3

## Ranges ##

In [23]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [24]:
np.arange(6) # gives us an array from 0 to 6, not including 6

array([0, 1, 2, 3, 4, 5])

In [25]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [26]:
np.arange(5, 11) # gives us an array from 5 to 11, not including 11

array([ 5,  6,  7,  8,  9, 10])

In [27]:
np.arange(0, 20, 2) # from 0 up to 20, by a step of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
np.arange(0, 21, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [29]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [30]:
# give me an array that goes from 10 to 30, not including 30 by step of 3
#(10, 13, 16 .... 28)
np.arange(10, 30, 3)

array([10, 13, 16, 19, 22, 25, 28])

In [32]:
#now let's include 31
np.arange(10, 32, 3)

array([10, 13, 16, 19, 22, 25, 28, 31])

In [33]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [36]:
np.arange(2)

array([0, 1])

In [37]:
a = np.arange(8)

In [38]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
a.item(7)

7

## Creating a Table from Scratch ##

In [41]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'], dtype='<U8')

In [43]:
Table() #initialize a new, empty Table, not always necessary

In [44]:
# creating a new table, called southside and add a column called Streets
#and populate that Streets column, with the array above, called streets
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste

In [47]:
southside_blocks = southside.with_column('Blocks from campus', np.arange(4))

In [48]:
southside_blocks

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [49]:
streets_iv = make_array('del playa', 'sabado tarde','trigo', 'pasado')

In [51]:
iv = Table().with_column('Streets', streets_iv)
iv

Streets
del playa
sabado tarde
trigo
pasado

In [54]:
iv = iv.with_column('Blocks from beach', np.arange(4))

In [55]:
iv

Streets      | Blocks from beach
del playa    | 0
sabado tarde | 1
trigo        | 2
pasado       | 3

In [56]:
# give me the street that is 2 blocks from the beach
iv.item(2)

/opt/conda/lib/python3.7/site-packages/datascience/tables.py:222: FutureWarning: Implicit column method lookup is deprecated.
  warnings.warn("Implicit column method lookup is deprecated.", FutureWarning)


Streets | Blocks from beach
trigo   | 2

In [62]:
iv.where('Blocks from beach', 2)

Streets | Blocks from beach
trigo   | 2

In [58]:
iv.labels

('Streets', 'Blocks from beach')

In [59]:
iv.num_columns

2

In [60]:
iv.num_rows

4

## Reading a Table from a File  ##

In [63]:
du_bois = Table.read_table('data/du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [68]:
# Which group ("CLASS") spent the highest percentage on rent?
du_bois.sort('RENT', descending = True).take(0)

CLASS   | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
300-400 | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR

In [72]:
max(du_bois.column('RENT'))
# give me the name of the class, possibly using where
du_bois.where('RENT', 0.23).select('CLASS')

CLASS
300-400

In [73]:
du_bois.select('STATUS')

STATUS
POOR
POOR
FAIR
FAIR
COMFORTABLE
COMFORTABLE
WELL-TO-DO

In [74]:
du_bois.column('STATUS')

array(['POOR', 'POOR', 'FAIR', 'FAIR', 'COMFORTABLE', 'COMFORTABLE',
       'WELL-TO-DO'], dtype='<U11')

In [ ]:
du_bois.select('STATUS')

In [ ]:
du_bois.column('STATUS')

In [75]:
du_bois.column('ACTUAL AVERAGE')

array([ 139.1 ,  249.45,  335.66,  433.82,  547.  ,  880.  , 1125.  ])

In [76]:
du_bois.column('FOOD')

array([0.43, 0.47, 0.43, 0.37, 0.31, 0.37, 0.29])

In [77]:
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

array([ 59.813 , 117.2415, 144.3338, 160.5134, 169.57  , 325.6   ,
       326.25  ])

In [78]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois = du_bois.with_column(
    'Food $',
    food_dollars
)
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [79]:
# can you add a column with Taxes in $ amount to du_bois table



In [80]:
du_bois.set_format('FOOD', PercentFormatter)

CLASS         | ACTUAL AVERAGE | RENT | FOOD   | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 43.00% | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 47.00% | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 43.00% | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 37.00% | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 31.00% | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 37.00% | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 29.00% | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [81]:
du_bois.select('CLASS', 'ACTUAL AVERAGE', 'FOOD', 'Food $')

CLASS         | ACTUAL AVERAGE | FOOD   | Food $
100-200       | 139.1          | 43.00% | 59.813
200-300       | 249.45         | 47.00% | 117.241
300-400       | 335.66         | 43.00% | 144.334
400-500       | 433.82         | 37.00% | 160.513
500-750       | 547            | 31.00% | 169.57
750-1000      | 880            | 37.00% | 325.6
1000 and over | 1125           | 29.00% | 326.25

In [ ]:
du_bois.column('FOOD')

## Selecting data in a column ##

In [ ]:
movies = Table.read_table('data/movies_by_year_with_ticket_price.csv')
movies.show()

In [ ]:
gross_in_dollars = movies.column('Total Gross') * 1e6
tix_sold = gross_in_dollars / movies.column('Average Ticket Price')

In [ ]:
movies = movies.with_column('Tickets sold', tix_sold)

In [ ]:
movies.show(4)

In [ ]:
movies.set_format('Tickets sold', NumberFormatter)

In [ ]:
movies.plot('Year', 'Tickets sold')

In [ ]:
movies.where('Year', are.between(2000, 2005))

In [ ]:
movies.where('Year', 2002)

In [ ]:
movies.where('Year', are.equal_to(2002))

In [ ]:
movies.where('#1 Movie', are.containing('Harry Potter'))

In [ ]:
movies.take(np.arange(2, 5))