In [5]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## Comparison ##

In [6]:
3 > 1

True

In [7]:
type(3 > 1) # type(True) #boolean value

bool

In [8]:
True # python is case-sensitive

True

In [52]:
'true'

'true'

In [10]:
# when we are checking for equality, are two things equal to each other?
# we use ==, two equal signs
3 = 3 
# python is saying we can't overwrite existing quantitative values within python
# in this case, integers

SyntaxError: can't assign to literal (<ipython-input-10-c11ced535c9d>, line 3)

In [11]:
3 == 3.0

True

In [12]:
3 == 3.000001

False

In [13]:
# is 3 equal to 3.0000000000000001?

3 == 3.0000000000000001
# floating point error in python, 15-16 decimal places saved in memory 

True

In [14]:
10 != 2

True

In [15]:
x = 14
y = 3

In [16]:
x > 15

False

In [17]:
12 < x

True

In [18]:
x < 20

True

In [19]:
12 < x < 20

True

In [21]:
10 < x-y < 13 # x - y = 14 - 3 = 11
# 10 < 11 < 13

True

In [22]:
x > 13 and y < 3.14159

True

In [26]:
x < 13 or y > 3.14159


True

In [25]:
x = 3

## Comparisons with arrays

In [27]:
pets = make_array('cat', 'cat', 'dog', 'cat', 'dog', 'rabbit')

In [34]:
sum(pets == 'cat')
# we have 3 cats in our pets array

3

In [31]:
1 + 1 + 0 + 1 + 0 + 0

3

In [33]:
sum(make_array(True, True, False, True, False, False))

3

In [41]:
sum(pets == 'dog')

2

In [40]:
np.count_nonzero(pets == 'dog')
# there are 2 dogs in pets
# counting number of nonzeros, or 1s, which are representing Trues


2

In [43]:
x = np.arange(20, 31)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [44]:
x > 28

array([False, False, False, False, False, False, False, False, False,
        True,  True])

## Simulation

Let's play a game: we each roll a die. 

If my number is bigger: you pay me a dollar.

If they're the same: we do nothing.

If your number is bigger: I pay you a dollar.

Steps:
1. Find a way to simulate two dice rolls.
2. Compute how much money we win/lose based on the result.
3. Do steps 1 and 2 10,000 times.

### Conditional Statements

In [45]:
# Work in progress
def one_round(my_roll, your_roll):
    if my_roll > your_roll:
        return 1
    
    # if my_roll < your_roll:
    # do something here

In [46]:
one_round(4, 3)

1

In [47]:
one_round(2, 6) # no conditional statements were written for this scenario
# where i owe you money

In [108]:
# Final correct version
def one_round(my_roll, your_roll):
    if 6 >= my_roll >= 1 and 6 >= your_roll >= 1:
        #if type(my_roll) == np.int and type(your_roll) == np.int:
        if my_roll > your_roll: # 4, 3
            return 1 # owe Sharon $1
        elif your_roll > my_roll: # 1, 6
            return -1 # Sharon owes me $1
        elif your_roll == my_roll: # 3, 3
            return 0 # no money transferred
    #else:
       # return "Try again! Roll an integer between 1 and 6"
    else:
         return "Try again! Roll a number betweeen 1 and 6"


In [103]:
one_round(1.1, 1)
# nothing is outputted, let's add a detailed error message
# that says something about no decimals

'Try again! Roll an integer between 1 and 6'

In [104]:
one_round(6, 5)

1

In [105]:
one_round(7, -1)

'Try again! Roll a number betweeen 1 and 6'

### Random Selection

In [68]:
mornings = make_array('wake up', 'sleep in')
mornings

array(['wake up', 'sleep in'], dtype='<U8')

In [76]:
np.random.choice(mornings)

'wake up'

In [70]:
np.random.choice(mornings)

'sleep in'

In [71]:
np.random.choice(mornings)

'wake up'

In [77]:
np.random.choice(mornings, 7)

array(['sleep in', 'wake up', 'wake up', 'sleep in', 'sleep in',
       'wake up', 'wake up'], dtype='<U8')

In [80]:
sum(np.random.choice(mornings, 7) == 'wake up')

3

In [82]:
np.count_nonzero(np.random.choice(mornings, 7) == 'sleep in')

5

In [85]:
morning_week = np.random.choice(mornings, 7)
morning_week

array(['wake up', 'wake up', 'wake up', 'wake up', 'wake up', 'wake up',
       'wake up'], dtype='<U8')

In [86]:
morning_week

array(['wake up', 'wake up', 'wake up', 'wake up', 'wake up', 'wake up',
       'wake up'], dtype='<U8')

In [89]:
sum(morning_week == 'wake up')

7

In [90]:
sum(morning_week == 'sleep in')

0

In [99]:
die_faces = np.arange(1, 7)
type(die_faces.item(0))

int

In [92]:
np.random.choice(die_faces)

4

In [113]:
def simulate_one_round():
    my_roll = np.random.choice(die_faces) # my_roll will be a random selection
    # from die_faces (1, 2, 3, 4, 5, 6)
    your_roll = np.random.choice(die_faces)# so will your_roll
    print(my_roll, your_roll)
    #print(type(my_roll), type(your_roll))
    return one_round(my_roll, your_roll) # 

In [114]:
simulate_one_round()

3 4


-1

### Appending Arrays

In [117]:
first = np.arange(4)
second = np.arange(10, 17)
first, second

(array([0, 1, 2, 3]), array([10, 11, 12, 13, 14, 15, 16]))

In [118]:
np.append(first, 6)

array([0, 1, 2, 3, 6])

In [119]:
first

array([0, 1, 2, 3])

In [120]:
np.append(first, second)

array([ 0,  1,  2,  3, 10, 11, 12, 13, 14, 15, 16])

In [121]:
first

array([0, 1, 2, 3])

In [122]:
second

array([10, 11, 12, 13, 14, 15, 16])

### Repeated Betting ###

In [ ]:
results = make_array()

In [ ]:
results = np.append(results, simulate_one_round())
results

## `For` Statements

In [ ]:
for pet in make_array('cat', 'dog', 'rabbit'):
    print('I love my ' + pet)

In [ ]:
pet = make_array('cat', 'dog', 'rabbit').item(0)
print('I love my ' + pet)

pet = make_array('cat', 'dog', 'rabbit').item(1)
print('I love my ' + pet)

pet = make_array('cat', 'dog', 'rabbit').item(2)
print('I love my ' + pet)

In [ ]:
game_outcomes = make_array()

for i in np.arange(5):
    game_outcomes = np.append(game_outcomes, simulate_one_round())
    
game_outcomes

In [ ]:
game_outcomes = make_array()

for i in np.arange(10000):
    game_outcomes = np.append(game_outcomes, simulate_one_round())
    
game_outcomes

In [ ]:
len(game_outcomes)

In [ ]:
results = Table().with_column('My winnings', game_outcomes)

In [ ]:
results

In [ ]:
results.group('My winnings').barh('My winnings')

In [ ]:
# Bonus question: This simulation is relatively simple. 
# Can you find a way to run it without using a for loop?





### Another example: simulating heads in 100 coin tosses

In [ ]:
coin = make_array('heads', 'tails')

In [ ]:
sum(np.random.choice(coin, 100) == 'heads')

In [ ]:
# Simulate one outcome

def num_heads():
    return sum(np.random.choice(coin, 100) == 'heads')

In [ ]:
# Decide how many times you want to repeat the experiment

repetitions = 10000

In [ ]:
# Simulate that many outcomes

outcomes = make_array()

for i in np.arange(repetitions):
    outcomes = np.append(outcomes, num_heads())

In [ ]:
heads = Table().with_column('Heads', outcomes)
heads.hist(bins = np.arange(29.5, 70.6))

## Optional: Advanced `where` ##

In [ ]:
ages = make_array(16, 22, 18, 15, 19, 15, 16, 21)
age = Table().with_column('Age', ages)

In [ ]:
age

In [ ]:
age.where('Age', are.above_or_equal_to(18))

In [ ]:
voter = ages >= 18

In [ ]:
voter

In [ ]:
age.where(voter)

In [ ]:
is_voter = are.above_or_equal_to(18)

In [ ]:
type(is_voter)

In [ ]:
is_voter(22)

In [ ]:
is_voter(3)

In [ ]:
age.apply(is_voter, 'Age')

In [ ]:
ages >= 18

In [ ]:
voter

In [ ]:
def my_voter_function(x):
    return x >= 18

In [ ]:
age.where('Age', are.above_or_equal_to(18))

In [ ]:
age.where(voter)

In [ ]:
age.where('Age', my_voter_function)